# Generated by Django 3.0 on 2020-05-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('administrator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('govner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chefZoneLeader', models.CharField(max_length=30)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chefQuarter', models.CharField(max_length=30)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('NomPere', models.CharField(max_length=20)),
                ('NomMere', models.CharField(max_length=20)),
                ('colline', models.CharField(max_length=20)),
                ('commune_natal', models.CharField(max_length=20)),
                ('province_natal', models.CharField(max_length=20)),
                ('anneeDeNaissance', models.CharField(max_length=20)),
                ('nationalite', models.CharField(max_length=20)),
                ('etatCivil', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('numberId', models.CharField(max_length=20)),
                ('date_delivrated', models.DateField()),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province'),
        ),
    ]
