# Generated by Django 3.0 on 2020-04-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentiteComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestionId', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('Person', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='identiteCompletes', to='account.Person')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Commune')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Quarter')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Zone')),
            ],
        ),
    ]
