# Generated by Django 3.0 on 2020-05-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentiteComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('attestionId', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Commune')),
                ('persone', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='identites', to='account.Person')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Quarter')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Zone')),
            ],
        ),
    ]
